### ISSUE TITLE
Dialog API

### ISSUE THREAD

**Issue by j2969719** [ivanenko/ydisk_commander#1]
> использует библиотеку GTK2

по идее с extension.h из sdk можно сделать диалоги без привязки к конкретному тулкиту 
у плагина ftp вроде так сделано

**Comment by ivanenko** [comment]
О, спасибо, не знал. Там оказывается целое DialogAPI. Жаль не документированное только

**Comment by j2969719** [comment]
бтв, doublecmd по идее еще может language/ydisk_commander.ru.po какой подхватить
